### ISSUE TITLE
我直接编译不能过，defined(RTE_Compiler_EventRecorder) && !defined(__PERF_COUNTER__)冲突了

### ISSUE THREAD

**Issue by Dreamfantcy** [GorgonMeducer/Pico_Template#4]
直接下载的工程RTE_Compiler_EventRecorder和__PERF_COUNTER__同时开启，但是此时EventRecorderTimerGetCount等函数就不会被编译

**Comment by GorgonMeducer** [comment]
请更新 perf_counter 到 2.1.0

**Comment by GorgonMeducer** [comment]
@Dreamfantcy 请问问题解决了么？
如果遇到升级 perf_counter 2.1.0 以后，RTE里 Utilities变成红色，只需要把Utilities所有内容全部取消、保存、关闭工程，然后重新打开工程，重新在RTE里选择 perf_counter 就能解决了。

**Comment by Dreamfantcy** [comment]
现在已经解决, 赞!
